################################################################################
# ML.NET's PR validation build
################################################################################

resources:
  containers:
  - container: LinuxContainer
    image: microsoft/dotnet-buildtools-prereqs:centos-7-b46d863-20180719033416

phases:

- template: /build/ci/phase-template.yml
  parameters:
    name: Centos
    buildScript: ./build.sh
    customMatrixes:
      Build_Debug_Intrinsics:
        _configuration: Debug-Intrinsics
        _config_short: DI
      Build_Release:
        _configuration: Release
        _config_short: R
    queue:
      name: Hosted Ubuntu 1604
      container: LinuxContainer

- template: /build/ci/phase-template.yml
  parameters:
    name: MacOS
    buildScript: ./build.sh
    queue:
      name: Hosted macOS

- template: /build/ci/phase-template.yml
  parameters:
    name: Windows_x64
    buildScript: build.cmd
    queue:
      name: Hosted VS2017
